FROM node:19.6.1-alpine3.17 as builder
WORKDIR /usr/src/app

COPY .env .
COPY package.json .
RUN npm install
COPY . .
RUN npm run build
RUN rm .env

FROM nginx
# COPY --from=builder /usr/src/app/build /usr/share/nginx/html

RUN rm /etc/nginx/conf.d/default.conf
COPY ./nginx.conf /etc/nginx/conf.d

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]